sensor_kit_base_link:
  camera_top/camera_link:
    x: -0.48575108346287643
    y: 0.023797377588446356
    z: 2.14975087450123
    roll: -1.8792639708245127
    pitch: -0.026130675034177903
    yaw: -1.5687327492415095
  camera_right/camera_link:
    x: -0.12721066651543367
    y: -1.2313034108857661
    z: 0.4986871206117457
    roll: -1.6536940570319605
    pitch: 0.18431832084914368
    yaw: 2.8194900709053674
  camera_left/camera_link:
    x: -0.21708213989510966
    y: 1.284272673668214
    z: 0.516539498874989
    roll: -1.613672013826762
    pitch: -0.19205608442835911
    yaw: 0.38576050943786033
  velodyne_front:
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0
  velodyne_left:
    x: -0.209462
    y: 1.27408
    z: 0.42718
    roll: 0.11323573304824952
    pitch: -0.15690236136798336
    yaw: -0.5679267064422931
  velodyne_right:
    x: -0.121292
    y: -1.20668
    z: 0.435086
    roll: -0.0823529587774486
    pitch: -0.1887974578284217
    yaw: 0.5687615129507895
#  gnss_ins:
#    x: -0.1062
#    y: 0.0
#    z: -0.1129
#    roll: -1.745332961713733
#    pitch: 6.378455042477681
#    yaw: 1.5707999441957374
#  gnss_ins_corrected:
#    x: -0.1062
#    y: 0.0
#    z: -0.1129
#    roll: 0.0
#    pitch: -0.1745329617148868
#    yaw: 0.0
  gnss_ins:
    x: -6.042
    y: 0.177
    z: -1.397
    roll: 0.037
    pitch: -0.200
    yaw: 0.00
